### ISSUE TITLE
Do we need to replicate Pantheon's existing admin cache UI in this plugin?

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/pantheon-integrated-cdn#2]
The Pantheon WordPress upstream mu plugin produces some existing admin UI:

![image](https://cloud.githubusercontent.com/assets/36432/19453756/6c5fccd4-946b-11e6-9644-fc5e9b7f5522.png)

![image](https://cloud.githubusercontent.com/assets/36432/19453775/7b8c30bc-946b-11e6-838f-04359b1b6295.png)

Do we need to replicate these features within the new plugin, or will these features remain the domain of the upstream mu plugin?

**Comment by kibra** [comment]
We're going to continue supporting this functionality in the upstream plugin: https://github.com/pantheon-systems/WordPress/issues/84
